% This script generates 6+1 connectivity matrices of size (6x6). Using the
% regions_83_to_6.mat file, which groups the different networks of the
% brain to effectively compress the 83 nodes into 6, 6 connectivity
% matrices are generated by picking only 6 of the most functionally
% well-connected nodes from Corr_FMRI. The last connectivity matrix (the
% +1) is the whole brain network, where the 6 subnetworks are each
% represented by 1 node.

% In summary, this script makes 6 connectivity matrices representing
% sub-systems in the brain, and 1 connectivity matrix representing the
% whole brain. The 7 matrices are all size 6x6.

clear all
clc

load regions_83_to_6.mat % The grouping matrix which tells which nodes correspond to which networks.
load Corr_FMRI.mat % The matrix from which the most functionally connected nodes are selected
load MJ_all.mat % The structural connectivity matrix to be modified/compressed.


Corr_FMRI = Corr_FMRI; 
% When this script is applied to the propofol data, this correlations
% matrix will change w.r.t. the timeseries data given. 


J_subNet = zeros(6,6,6);
J_brain = zeros(6); 
indice_map = zeros(6,6);

% Generate the 6 network connectivity matrices
% The 6 most connected nodes in each network will be the represantative
% nodes of the network
for i = 1:size(region,1)
    ind = region(i,logical(region(i,:))); % gets rid of zeros
    MatTemp = Corr_FMRI(ind,ind); % makes a smaller J with only ROI
    [~,ind_sort]=sort(sum(MatTemp),'descend');
    % orders the connectivity such that the most well connected regions are
    % first and spits out the indices in descending order
    
    indice_map(i,:) = ind(ind_sort(1:6));
    J_subNet(:,:,i) = MJ_all_mn(indice_map(i,:),indice_map(i,:));
    J_subNet(:,:,i) = J_subNet(:,:,i)./max(max(J_subNet(:,:,i)));
    
%     figure(1)
%     imagesc(J_subNet(:,:,i))
%     title(num2str(i))
%     figure(2)
%     hist(J_subNet(:,:,i)')
%     title(num2str(i))
%     pause()
end



% Generate the whole brain connectivity matrix This loops uses the indice
% map from above to average the connectivity over all nodes within a
% network, thereby generating a 6x6 connectivity matrix representative of
% the whole brain grouped into its 6 main networks
for i = 1:size(indice_map,1)
    ind1 = indice_map(i,:);
    
    for j = (i+1):size(indice_map,1);
        ind2 = indice_map(j,:);
        J_brain(i,j) = mean(mean(MJ_all_mn(ind1,ind2)));
        % averages the connectivity between two networks
    end
end

% ---\\ SELF CONNECTIONS? //---

J_brain = triu(J_brain) + triu(J_brain,1)';
J_brain = J_brain./max(max(J_brain));

clearvars -except J_subNet J_brain indice_map

% In indice_map matrix (and J_brain), each row represents the following
% regions: Auditory, DMN, ECN (left and right), Salience, Sensorimotor,
% Visual (L,M,O) for a total of 6 regions.

% NOTE: These regions have overlapping indices. For example: 75 - Auditory
% (3rd), Salience (4th) 60 - DMN (3rd), ECN (1st) 20 - DMN (2nd), ECN (5th)
% 15 - DMN (4th), ECN (6th)